// This file is auto-generated by the Firebase CLI.
// Do not edit it manually.
import * as functions from "firebase-functions";
import * as admin from "firebase-admin";
import * as nodemailer from "nodemailer";

import { syncCalendar } from "./ai/flows/sync-calendar-flow.js";

// Initialize the Firebase Admin SDK
admin.initializeApp();
const db = admin.firestore();

// Configure the email transport using the default SMTP transport and a GMail account.
const mailTransport = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: "strm.line.app@gmail.com", // TODO: Configure this with your email
    pass: "12345", // TODO: Configure this with your app password
  },
});

/**
 * Helper function to get all administrator emails from Firestore for a specific workspace.
 */
async function getAdminEmails(workspaceId: string): Promise<string[]> {
  const adminsRef = db.collection("users").where("isAdmin", "==", true).where("workspaceId", "==", workspaceId);
  const snapshot = await adminsRef.get();
  const adminEmails: string[] = [];
  snapshot.forEach((doc) => {
    const user = doc.data();
    if (user.email) {
      adminEmails.push(user.email);
    }
  });
  return adminEmails;
}

/**
 * Sends an email using Nodemailer.
 */
export async function sendEmail(to: string[], subject: string, htmlBody: string): Promise<void> {
  const mailOptions = {
    from: "AgileFlow Notifications <noreply@firebase.com>",
    to: to.join(","),
    subject: subject,
    html: htmlBody,
  };
  try {
    await mailTransport.sendMail(mailOptions);
    functions.logger.log("Email sent successfully to:", to.join(","));
  } catch (error) {
    functions.logger.error("There was an error while sending the email:", error);
  }
}

/**
 * Firestore trigger that sends an email to admins when a new user signs up.
 */
export const onNewUserCreated = functions.firestore
  .document("users/{userId}")
  .onCreate(async (snap) => {
    const newUser = snap.data();
    if (!newUser || newUser.accountType !== "Viewer" || !newUser.workspaceId) {
      console.log("User does not require approval or has no workspaceId. Exiting function.");
      return null;
    }
    const newUserName = newUser.displayName || "A new user";
    const newUserEmail = newUser.email || "No email provided";
    const workspaceId = newUser.workspaceId;
    console.log(`New user "${newUserName}" requires approval for workspace "${workspaceId}".`);

    const adminEmails = await getAdminEmails(workspaceId);
    if (adminEmails.length === 0) {
      console.log("No administrators found to notify for this workspace. Exiting function.");
      return null;
    }

    const subject = `AgileFlow: New User Awaiting Approval - ${newUserName}`;
    const htmlBody = `
      <p>A new user has signed up and is awaiting your approval:</p>
      <ul>
          <li><strong>Name:</strong> ${newUserName}</li>
          <li><strong>Email:</strong> ${newUserEmail}</li>
      </ul>
      <p>Please log in to the AgileFlow admin dashboard to approve or reject this user.</p>
      <p><a href="https://your-agileflow-app.com/dashboard/notifications">View Pending Users</a></p>
    `;
    try {
      await sendEmail(adminEmails, subject, htmlBody);
    } catch (error) {
      console.error("Error sending email:", error);
    }
    return null;
  });

/**
 * Firestore trigger that sends an invitation email when a new email is added
 * to the pre-approved-emails collection.
 */
export const sendInvitation = functions.firestore
  .document("pre-approved-emails/{docId}")
  .onCreate(async (snap) => {
    const newInvitation = snap.data();
    if (!newInvitation) {
      console.log("No data found in event.");
      return null;
    }
    const { email, invitedBy, workspaceId } = newInvitation;
    if (!email || !invitedBy || !workspaceId) {
      console.log("Missing required fields in invitation document.");
      return null;
    }
    let inviterName = "An administrator";
    try {
      const userDoc = await db.collection("users").doc(invitedBy).get();
      if (userDoc.exists) {
        inviterName = userDoc.data()?.displayName || inviterName;
      }
    } catch (error) {
      console.error(`Failed to fetch inviter's name for userId: ${invitedBy}`, error);
    }
    const subject = `You're invited by ${inviterName} to join AgileFlow!`;
    const htmlBody = `
      <p>Hi there,</p>
      <p>${inviterName} has invited you to join your team on AgileFlow.</p>
      <p>Please click the link below to sign up and get started:</p>
      <p><a href="https://agileflow-mlf18.web.app/login">Sign Up for AgileFlow</a></p>
      <p>If you have any questions, please contact your workspace administrator.</p>
    `;
    try {
      await sendEmail([email], subject, htmlBody);
      console.log(`Invitation email sent successfully to ${email}.`);
    } catch (error) {
      console.error(`Error sending invitation email to ${email}:`, error);
    }
    return null;
  });

/**
 * Finds the internal calendar document and its workspaceId based on the googleCalendarId.
 */
async function getWorkspaceForCalendar(googleCalendarId: string): Promise<{ workspaceId: string } | null> {
    const calendarsRef = db.collection("calendars");
    const q = calendarsRef.where("googleCalendarId", "==", googleCalendarId).limit(1);
    const snapshot = await q.get();

    if (snapshot.empty) {
        functions.logger.warn(`No internal calendar found for googleCalendarId: ${googleCalendarId}`);
        return null;
    }
    const calendarDoc = snapshot.docs[0];
    const calendarData = calendarDoc.data();
    if (!calendarData.workspaceId) {
        functions.logger.error(`Internal calendar ${calendarDoc.id} is missing a workspaceId.`);
        return null;
    }
    return { workspaceId: calendarData.workspaceId };
}

/**
 * This function is triggered by an HTTP POST request from the Google Calendar API.
 * It processes the notification and triggers a sync for the relevant calendar.
 */
export const calendarWebhook = functions.https.onRequest(async (request, response) => {
    // Google sends a 'sync' header to verify the webhook endpoint upon creation.
    if (request.headers["x-goog-channel-state"] === "sync") {
        functions.logger.info("Received sync request from Google Calendar API, webhook is verified.");
        response.status(200).send();
        return;
    }

    const googleCalendarId = request.headers["x-goog-resource-id"];
    if (typeof googleCalendarId !== "string") {
        functions.logger.warn("Received a notification without a valid resource ID.", { headers: request.headers });
        response.status(400).send("Bad Request: Missing Google Calendar resource ID.");
        return;
    }

    functions.logger.info(`Received update notification for calendar: ${googleCalendarId}`);

    try {
        // Find the workspace associated with this Google Calendar ID.
        const context = await getWorkspaceForCalendar(googleCalendarId);
        if (!context) {
            response.status(404).send("No workspace configured for this calendar.");
            return;
        }

        const { workspaceId } = context;

        // Trigger the Genkit sync flow with the required workspace context.
        await syncCalendar({ googleCalendarId, workspaceId });
        functions.logger.info(`Successfully triggered sync for calendar: ${googleCalendarId} in workspace: ${workspaceId}`);
        response.status(200).send("Sync triggered successfully.");
    } catch (error) {
        functions.logger.error(`Failed to trigger sync for calendar ${googleCalendarId}`, error);
        response.status(500).send("Internal Server Error.");
    }
});
